
import React from 'react';

export const SECTORS = ['Agriculture', 'Tech', 'Crafts', 'Food & Beverage', 'Services', 'Retail'];
export const LOCATIONS = ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Bekaa', 'Mount Lebanon'];

export const CATEGORY_LABELS: Record<string, { EN: string, AR: string }> = {
  'Agriculture': { EN: 'Agriculture', AR: 'الزراعة' },
  'Tech': { EN: 'Technology', AR: 'التكنولوجيا' },
  'Crafts': { EN: 'Crafts', AR: 'الحرف اليدوية' },
  'Food & Beverage': { EN: 'Food & Beverage', AR: 'الأغذية والمشروبات' },
  'Services': { EN: 'Services', AR: 'الخدمات' },
  'Retail': { EN: 'Retail', AR: 'تجارة التجزئة' },
};

export const LOCATION_LABELS: Record<string, { EN: string, AR: string }> = {
  'Beirut': { EN: 'Beirut', AR: 'بيروت' },
  'Tripoli': { EN: 'Tripoli', AR: 'طرابلس' },
  'Sidon': { EN: 'Sidon', AR: 'صيدا' },
  'Tyre': { EN: 'Tyre', AR: 'صور' },
  'Bekaa': { EN: 'Bekaa', AR: 'البقاع' },
  'Mount Lebanon': { EN: 'Mount Lebanon', AR: 'جبل لبنان' },
};

export const CURRENCY_LABELS: Record<string, { EN: string, AR: string }> = {
  'USD': { EN: 'USD', AR: 'دولار' },
  'SYP': { EN: 'SYP', AR: 'ل.س' },
  'TRY': { EN: 'TRY', AR: 'ل.ت' },
};

export const UI_STRINGS = {
  EN: {
    marketplace: 'Marketplace',
    academy: 'Mini-Academy',
    monitoringPlural: 'Projects Monitoring',
    monitoringSingular: 'Project Monitoring',
    network: 'Experience Sharing',
    dashboard: 'Dashboard',
    admin: 'Admin Console',
    login: 'Login',
    logout: 'Logout',
    search: 'Search products...',
    filter: 'Filter by',
    all: 'All',
    sector: 'Category',
    location: 'Location',
    active: 'Active',
    inactive: 'Inactive',
    emerging: 'Emerging',
    reportTitle: 'Monthly Report',
    sales: 'Sales',
    totalSales: 'Total Sales',
    networkTitle: 'Experience Sharing',
    adminTitle: 'Projects Monitoring',
    directory: 'Project Directory',
    userManagement: 'User Management',
    websiteSettings: 'Website Settings',
    welcome: 'Welcome',
    viewPublic: 'View Public Page',
    editProfile: 'Edit Profile',
    addNew: 'Add New...',
    save: 'Save',
    cancel: 'Cancel',
    productName: 'Product Name',
    price: 'Price',
    currency: 'Currency',
    details: 'Details',
    uploadImage: 'Upload Image',
    saveProduct: 'Save Product',
    noProducts: 'No products found.',
    noBusinesses: 'No businesses found.',
    storeStatus: 'Store Status',
    open: 'Open',
    closed: 'Closed',
    automatic: 'Automatic',
    startTime: 'Opening Time',
    endTime: 'Closing Time',
    projectLogo: 'Project Logo',
    projectSubtitle: 'Project Subtitle (Optional)',
    projectDescription: 'Project Description',
    governorate: 'Governorate',
    city: 'City',
    pinMap: 'Pin on Map',
    locationDirections: 'Location Directions (Optional)',
    categoryInherited: 'Inherited from Store',
    academyManagement: 'Academy Management',
    addMaterial: 'Add Material',
    lessonTitle: 'Lesson Title',
    newAcademyAlert: 'New Content Added to Academy!',
    analytics: 'Analytics',
    topPerforming: 'Top Projects',
    bestSelling: 'Best-Selling Products',
    hotspots: 'Geographic Hotspots',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    conversionRate: 'Conversion Rate',
    status: 'Status',
    role: 'Role',
    permissions: 'Permissions',
    delete: 'Delete',
    edit: 'Edit',
    superAdmin: 'Super Admin',
    manager: 'Manager',
    sliderManager: 'Hero Slider Manager',
    showSlider: 'Show Slider on Home Page',
    branding: 'Branding & Identity',
    styling: 'Styling Control',
    primaryColor: 'Primary Color',
    fontFamily: 'Font Family',
    mainTitle: 'Website Title',
    mainSubtitle: 'Website Subtitle',
    footerText: 'Footer Copyright Text',
    refreshData: 'Refresh Data',
    performanceRank: 'Performance Rankings',
    stockStatus: 'Stock Status',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    limited: 'Limited',
    quantity: 'Quantity',
    isPublished: 'Publish Online',
    specifications: 'Specifications',
    addSpec: 'Add Spec',
    productDescription: 'Product Description',
    productGallery: 'Product Gallery',
    businessName: 'Business Name',
    emailAddress: 'Email Address',
    share: 'Share',
    copyLink: 'Copy Link',
    copied: 'Copied!',
    qrCode: 'QR Code',
    challenges: 'Challenges',
    // Missing strings for Identity Toolkit
    toolkitTitle: 'Identity Toolkit',
    businessCard: 'Business Card',
    downloadPdf: 'Download PDF',
    qrCodeTitle: 'QR Code',
    downloadPng: 'Download PNG',
    aiHelper: 'AI Content Helper',
    generateCaptions: 'Generate Captions',
    forum: 'The Forum',
    createPost: 'Create Post',
    writeYourThoughts: 'Share your thoughts, ideas, and experiences...',
    addImages: 'Add Images',
    addVideos: 'Add Videos',
    addFiles: 'Add Files',
    embedYoutube: 'Embed YouTube',
    post: 'Post',
    like: 'Like',
    love: 'Love',
    haha: 'Haha',
    wow: 'Wow',
    sad: 'Sad',
    angry: 'Angry',
    comment: 'Comment',
    comments: 'Comments',
    reply: 'Reply',
    deletePost: 'Delete Post',
    deleteComment: 'Delete Comment',
    editPost: 'Edit Post',
    editComment: 'Edit Comment',
    banFromForum: 'Ban from Forum',
    banFromMarket: 'Ban from Market',
    unban: 'Unban',
    banReason: 'Ban Reason',
    moderationTools: 'Moderation Tools',
    deleteContent: 'Delete Content',
    contentModeration: 'Content Moderation',
    userBans: 'User Bans',
    bannedUsers: 'Banned Users',
    banUser: 'Ban User',
    noComments: 'No comments yet. Be the first to comment!',
    reactions: 'Reactions',
    reactionCount: 'people reacted',
    youReacted: 'You reacted',
    fileUploadError: 'File upload failed',
    maxFileSize: 'Maximum file size is 10MB',
    supportedFormats: 'Supported formats: JPG, PNG, MP4, PDF, DOC, DOCX'
  },
  AR: {
    marketplace: 'السوق الرقمي',
    academy: 'الأكاديمية المصغرة',
    monitoringPlural: 'مراقبة المشاريع',
    monitoringSingular: 'مراقبة المشروع',
    network: 'مشاركة الخبرات',
    dashboard: 'لوحة التحكم',
    admin: 'إدارة النظام',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    search: 'البحث عن منتجات...',
    filter: 'تصفية حسب',
    all: 'الكل',
    sector: 'الفئة',
    location: 'الموقع',
    active: 'نشط',
    inactive: 'غير نشط',
    emerging: 'ناشئ',
    reportTitle: 'التقرير الشهري',
    sales: 'المبيعات',
    totalSales: 'إجمالي المبيعات',
    networkTitle: 'مشاركة الخبرات',
    adminTitle: 'مراقبة المشاريع',
    directory: 'دليل المشاريع',
    userManagement: 'إدارة المستخدمين',
    websiteSettings: 'إعدادات الموقع',
    welcome: 'أهلاً بك',
    viewPublic: 'عرض الصفحة العامة',
    editProfile: 'تعديل الملف الشخصي',
    addNew: 'إضافة جديد...',
    save: 'حفظ',
    cancel: 'إلغاء',
    productName: 'اسم المنتج',
    price: 'السعر',
    currency: 'العملة',
    details: 'التفاصيل',
    uploadImage: 'رفع صورة',
    saveProduct: 'حفظ المنتج',
    noProducts: 'لم يتم العثور على منتجات.',
    noBusinesses: 'لم يتم العثور على مشاريع.',
    storeStatus: 'حالة المتجر',
    open: 'مفتوح',
    closed: 'مغلق',
    automatic: 'تلقائي',
    startTime: 'وقت الافتتاح',
    endTime: 'وقت الإغلاق',
    projectLogo: 'شعار المشروع',
    projectSubtitle: 'العنوان الفرعي للمشروع (اختياري)',
    projectDescription: 'وصف المشروع',
    governorate: 'المحافظة',
    city: 'المدينة',
    pinMap: 'تحديد على الخريطة',
    locationDirections: 'اتجاهات الموقع (اختياري)',
    categoryInherited: 'مورث من المتجر',
    academyManagement: 'إدارة الأكاديمية',
    addMaterial: 'إضافة مادة تعليمية',
    lessonTitle: 'عنوان الدرس',
    newAcademyAlert: 'تمت إضافة محتوى جديد في الأكاديمية!',
    analytics: 'التحليلات',
    topPerforming: 'أفضل المشاريع',
    bestSelling: 'المنتجات الأكثر مبيعاً',
    hotspots: 'المناطق النشطة',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    conversionRate: 'معدل التحويل',
    status: 'الحالة',
    role: 'الدور',
    permissions: 'الصلاحيات',
    delete: 'حذف',
    edit: 'تعديل',
    superAdmin: 'مدير خارق',
    manager: 'مدير',
    sliderManager: 'إدارة سلايدر الصفحة الرئيسية',
    showSlider: 'عرض السلايدر في الصفحة الرئيسية',
    branding: 'الهوية والعلامة التجارية',
    styling: 'التحكم في المظهر',
    primaryColor: 'اللون الأساسي',
    fontFamily: 'نوع الخط',
    mainTitle: 'عنوان الموقع',
    mainSubtitle: 'العنوان الفرعي للموقع',
    footerText: 'نص الحقوق في الأسفل',
    refreshData: 'تحديث البيانات',
    performanceRank: 'ترتيب الأداء',
    stockStatus: 'حالة التوفر',
    inStock: 'متوفر',
    outOfStock: 'نفد',
    limited: 'محدود',
    quantity: 'الكمية',
    isPublished: 'نشر على الموقع',
    specifications: 'المواصفات',
    addSpec: 'إضافة مواصفة',
    productDescription: 'وصف المنتج',
    productGallery: 'معرض صور المنتج',
    businessName: 'اسم المشروع',
    emailAddress: 'البريد الإلكتروني',
    share: 'مشاركة',
    copyLink: 'نسخ الرابط',
    copied: 'تم النسخ!',
    qrCode: 'رمز QR',
    challenges: 'التحديات',
    // Strings for Identity Toolkit
    toolkitTitle: 'حقيبة الهوية البصرية',
    businessCard: 'بطاقة العمل',
    downloadPdf: 'تحميل PDF',
    qrCodeTitle: 'رمز QR',
    downloadPng: 'تحميل PNG',
    aiHelper: 'مساعد المحتوى الذكي',
    generateCaptions: 'توليد تعليقات',
    forum: 'المنتدى',
    createPost: 'إنشاء منشور',
    writeYourThoughts: 'شارك أفكارك وخبراتك...',
    addImages: 'إضافة صور',
    addVideos: 'إضافة فيديو',
    addFiles: 'إضافة ملفات',
    embedYoutube: 'إدراج YouTube',
    post: 'نشر',
    like: 'إعجاب',
    love: 'حب',
    haha: 'ضحك',
    wow: 'مندهش',
    sad: 'حزين',
    angry: 'غضب',
    comment: 'تعليق',
    comments: 'تعليقات',
    reply: 'رد',
    deletePost: 'حذف المنشور',
    deleteComment: 'حذف التعليق',
    editPost: 'تعديل المنشور',
    editComment: 'تعديل التعليق',
    banFromForum: 'منع من المنتدى',
    banFromMarket: 'منع من المتجر',
    unban: 'رفع الحظر',
    banReason: 'سبب الحظر',
    moderationTools: 'أدوات الإشراف',
    deleteContent: 'حذف المحتوى',
    contentModeration: 'إشراف المحتوى',
    userBans: 'حظر المستخدمين',
    bannedUsers: 'المستخدمون المحظورون',
    banUser: 'حظر المستخدم',
    noComments: 'لا توجد تعليقات حتى الآن. كن أول من يعلق!',
    reactions: 'التفاعلات',
    reactionCount: 'أشخاص تفاعلوا',
    youReacted: 'أنت تفاعلت',
    fileUploadError: 'فشل رفع الملف',
    maxFileSize: 'الحد الأقصى لحجم الملف هو 10 ميجابايت',
    supportedFormats: 'الصيغ المدعومة: JPG, PNG, MP4, PDF, DOC, DOCX'
  }
};
